export const AppActionTypes = {
  SET_ACTIVE_PAGE: "SET_ACTIVE_PAGE",
  SET_CURRENT_LEVEL: "SET_CURRENT_LEVEL",
  TOGGLE_CHARACTER_MENU: "TOGGLE_CHARACTER_MENU",
  TOGGLE_INVENTORY_MENU: "TOGGLE_INVENTORY_MENU",
  TOGGLE_INVENTORY_CATEGORY: "TOGGLE_INVENTORY_CATEGORY",
  TOGGLE_LOGS_MENU: "TOGGLE_LOGS_MENU",
  TOGGLE_LOG_CATEGORY: "TOGGLE_LOG_CATEGORY",
  TOGGLE_INVENTORY_DEFAULT: "TOGGLE_INVENTORY_DEFAULT",
  SET_CURRENT_ITEM_DESCRIPTION: "SET_CURRENT_ITEM_DESCRIPTION",
};
